Development
codefordc/us-congress-pizza-flag-tracker-frontend pull request #94
Opened 2022-04-08 16:32 UTC by mertbagt

changed allowUpdate to be based on user.office_code instead of user.can_update_status_for

2022-04-11 20:02 UTC, ethanstrominger requested changes

2022-04-11 20:26 UTC, mertbagt commented on src/pages/scanOrder.js
> +    if (nextStatus.permission === "FED-HOSS" && user.office_code === "FED-HOSS")
done

2022-04-11 20:26 UTC, mertbagt commented on src/pages/scanOrder.js
> +    if (user.office_code === "FED-ADMIN") allowUpdate = "yes";
done

2022-04-11 20:57 UTC, mertbagt commented on src/pages/scanOrder.js
> +  if (user) {
done

2022-04-12 19:09 UTC, mertbagt commented on src/pages/scanOrder.js
> +  const calculateAllowUpdate = () => {
- [X] allowUpdate refactored 
- [ ] refactor lifeCycle
- [ ] rename lifeCycle

2022-04-13 22:51 UTC, mertbagt commented
![image](https://user-images.githubusercontent.com/73559781/163282692-081d61f7-32a4-4c98-a520-0e72ee8e6960.png)

2022-04-13 22:52 UTC, merged